### ISSUE TITLE
destructuring `defineProps` breaks reactivity

### ISSUE THREAD

**Issue by iStuffs** [Code-Pop/Real-World-Nuxt-3#1]
Reactivity transform is no loger part of Vue.
https://vuejs.org/guide/extras/reactivity-transform#reactivity-transform

So destructuring `defineProps` breaks reactivity.
We should use `toRefs` to destructure data from the props.

**Comment by tutorialcode** [comment]
There's no mutation in this app yet, the API data will stay the same, so it doesn't really matter the prop has reactivity or not. Also, you can do default props easily with destructuring.
